services:
  - type: web
    name: edox-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://edox-frontend.onrender.com
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false

  - type: web
    name: edox-frontend
    runtime: static
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        value: https://edox-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
